name: Call remote workflow action by pull request
on:
  pull_request:
jobs:
  call-remote:
    uses: shangerxin/github-workflow-demo/.github/workflows/remote-call.yml@main

  test-pr:
    needs: [call-remote]
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install upgrade
        run: |
          echo "Hello from test-pr"
